# -*- coding: utf-8 -*-
"""Khan_M_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZdfcYHs-j0gAhkDiztA5Eo8c09bXyX-
"""

import pandas as pd
import plotly.express as px

df = pd.read_excel("IA 4_LastYearSales.xlsx")

df.head()

fig = px.scatter(df, x="Temperature (°F)", y="GreenTote",
                 trendline="ols",
                 title="Correlation Between Sales and Temperature",
                 labels={"Temperature": "Temperature (°F)", "GreenTote": "GreenTote Sales Performance"},
                 opacity=0.6)
fig.show()

import pandas as pd
import plotly.graph_objects as go


df = pd.read_csv("Khan_Muhammad_sentiment.csv")

expected_categories = ["Positive", "Neutral", "Negative"]

sentiment_counts = df["Sentiment_Label"].value_counts().reindex(expected_categories, fill_value=0)

categories = sentiment_counts.index.tolist()
values = sentiment_counts.values.tolist()

color_map = {"Positive": "green", "Neutral": "gray", "Negative": "red"}
bar_colors = [color_map.get(sentiment, "blue") for sentiment in categories]


fig = go.Figure(data=[go.Bar(x=categories, y=values, marker=dict(color=bar_colors))])

fig.update_layout(title='Customer Sentiment Polarity Distribution',
                  xaxis_title='Sentiment Category',
                  yaxis_title='Number of Reviews',
                  template='plotly_white')

fig.show()

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
df = pd.read_csv("Khan_Muhammad_sentiment.csv")
df.head()

df['Sentiment_Label'] = df['Sentiment_Label'].str.lower()

positive_reviews = " ".join(df[df['Sentiment_Label'] == 'positive']['Review'].dropna())
neutral_reviews = " ".join(df[df['Sentiment_Label'] == 'neutral']['Review'].dropna())
negative_reviews = " ".join(df[df['Sentiment_Label'] == 'negative']['Review'].dropna())

def generate_wordcloud(text, color, title):
    wordcloud = WordCloud(width=800, height=400, background_color=color, colormap="coolwarm").generate(text)
    plt.figure(figsize=(8, 4))
    plt.imshow(wordcloud, interpolation="bilinear")
    plt.axis("off")
    plt.title(title, fontsize=14)
    plt.show()

generate_wordcloud(positive_reviews, "white", "Positive Reviews Word Cloud")
generate_wordcloud(neutral_reviews, "lightgray", "Neutral Reviews Word Cloud")
generate_wordcloud(negative_reviews, "black", "Negative Reviews Word Cloud")